name: CI/CD for EPL App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore backend/src/

      - name: Build
        run: dotnet build backend/src/ --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test backend/src/ --configuration Release --no-build

  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  docker:
    needs: [build-and-test-backend, build-and-test-frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t solty2212/epl-api-backend:latest backend/
          docker push solty2212/epl-api-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t solty2212/epl-api-frontend:latest frontend/
          docker push solty2212/epl-api-frontend:latest
